Update S51youtubeUnblock
Waujito/youtubeUnblock pull request #208
Opened 2024-12-31 17:35 UTC by HiHat

Entware style changes

2025-01-02 08:27 UTC, Waujito commented
Thank you!
Yeah, I completely forgot about daemonize flag and Entware. I will test it for a bit and merge.

2025-01-03 22:20 UTC, Waujito requested changes

2025-01-03 22:20 UTC, Waujito commented on youtubeUnblockEntware/files/S51youtubeUnblock
> +ARGS="--daemonize"
It is better to write --daemonize near the process

2025-01-03 22:20 UTC, Waujito commented on youtubeUnblockEntware/files/S51youtubeUnblock
> +	. /opt/etc/init.d/rc.func start $CALLER
I don't believe in this rc.func abstraction. I want to control everything here, inside the script. https://github.com/Entware/rtndev/blob/master/entware-opt/files/rc.func 

So, keep old runner but with --daemonize. Like `$PROCS $ARGS --daemonize`. Also with daemonize you don't have to /dev/null early output.

2025-01-03 22:20 UTC, Waujito commented on youtubeUnblockEntware/files/S51youtubeUnblock
> +#	echo -e "$ansi_white Started $PROCS $ansi_std"
Without rc.func abstraction this logger is ok.

2025-03-04 08:06 UTC, HiHat commented on youtubeUnblockEntware/files/S51youtubeUnblock
> +ARGS="--daemonize"
ok, please implement!

2025-03-11 12:14 UTC, HiHat commented
Please add --daemonize to entware init scipts!

2025-03-16 13:28 UTC, merged